modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/yzl210/MobFarmUtilities/issues"
logoFile="logo.png"
license = "GNU GPLv3"
[[mods]]
modId = "mobfarmutilities"
version = "${version}"
displayName = "Mob Farm Helpers"
authors = "6LeoMC"
credits = "Thanks to temhotaokeaha for the textures"
description = '''
Add some useful mob farm helpers
'''

[[dependencies.mobfarmutilities]]
modId = "architectury"
mandatory = true
versionRange = "[4.4.70,)"
ordering = "AFTER"
side = "BOTH"